# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode8
podfile: AKSideMenuExamples/Simple/Podfile

script:
- xcodebuild -workspace AKSideMenuExamples/Simple/AKSideMenuSimple.xcworkspace -scheme AKSideMenuSimple -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
